#!/bin/bash

echo "🌐 GitHub Pages部署验证脚本"
echo "========================================"
echo "🕐 开始时间: $(date)"
echo ""

# 预计GitHub Pages地址
GITHUB_PAGES="https://304269637.github.io/secret-treehouse"
RENDER_API="https://secret-treehouse-api.onrender.com"

echo "📋 预计部署地址:"
echo "🌐 前端页面: $GITHUB_PAGES"
echo "🔧 后端API: $RENDER_API"
echo ""

echo "🚀 部署步骤验证:"
echo "1. ✅ 访问GitHub仓库: https://github.com/304269637/secret-treehouse"
echo "2. ✅ 点击Settings → Pages"
echo "3. ✅ 配置: Source = main, Folder = /public"
echo "4. ✅ 点击Save，等待1-3分钟"
echo "5. ✅ 访问: $GITHUB_PAGES"
echo ""

echo "🔍 功能验证清单:"
echo ""
echo "📱 页面加载测试:"
echo "   1. 打开 $GITHUB_PAGES"
echo "   2. 应该看到树洞首页"
echo "   3. 页面标题: '🌳 匿名情绪树洞'"
echo ""
echo "💌 留言功能测试:"
echo "   1. 填写昵称 (可选)"
echo "   2. 选择情绪 (如: 😊 快乐)"
echo "   3. 输入留言内容"
echo "   4. 选择分类"
echo "   5. 点击'分享心事'按钮"
echo "   6. 应该看到成功提示"
echo ""
echo "📖 留言展示测试:"
echo "   1. 点击'查看大家的分享'"
echo "   2. 或访问: $GITHUB_PAGES/messages.html"
echo "   3. 应该看到留言列表"
echo ""
echo "📊 统计数据显示:"
echo "   1. 首页应该显示统计数据"
echo "   2. 总分享数、已回应数等"
echo ""
echo "🎨 响应式设计测试:"
echo "   1. 用手机访问页面"
echo "   2. 调整浏览器窗口大小"
echo "   3. 布局应该自适应"
echo ""

echo "🔄 后端API验证:"
echo "✅ 健康检查: $RENDER_API/api/health"
echo "✅ 留言列表: $RENDER_API/api/messages"
echo "✅ 统计数据: $RENDER_API/api/stats"
echo "✅ 分类数据: $RENDER_API/api/categories"
echo ""

echo "🆘 如果遇到问题:"
echo "1. ❌ 页面404: 检查GitHub Pages配置"
echo "2. ❌ API连接失败: 检查config.js中的API_BASE"
echo "3. ❌ 功能不正常: 检查浏览器控制台错误"
echo "4. 📸 截图错误信息发送给我"
echo ""

echo "🎯 成功标志:"
echo "✅ 前端页面可访问"
echo "✅ 所有功能正常工作"
echo "✅ 前后端通信正常"
echo "✅ 响应式设计正常"
echo ""

echo "========================================"
echo "🦞 小龙虾部署小队祝您部署顺利！"
echo "部署完成后请告诉我结果！"